export enum ROLES {
  ADMIN = 'ADMIN',
  INDIVIDUAL_USER = 'INDIVIDUAL_USER',
  ORG_USER = 'ORG_USER',
  ORG_ADMIN = 'ORG_ADMIN'
}

export enum SUPPORT_TICKET_STATUS {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  CLOSED = 'CLOSED'
}

export enum ADMIN_ROLES {
  SUPER_ADMIN = 'SUPER_ADMIN',
  LOCATION_ADMIN = 'LOCATION_ADMIN'
}